version: '3'

services:
  postgres:
    image: 'postgres:15'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_DB=employee_management'

  app:
    build: ./
    container_name: 'java-app'
    ports:
      - '8080:8080'
    env_file: .env
    depends_on:
      - postgres
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/employee_management'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=1234'